/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTargetingRouteImport } from './routes/_authenticated/targeting'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedApprovalRouteImport } from './routes/_authenticated/approval'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicWebhooksInboundEmailRouteImport } from './routes/api/public/webhooks.inbound-email'
import { Route as ApiPublicCronSendOutboundRouteImport } from './routes/api/public/cron.send-outbound'
import { Route as ApiPublicCronDailyAutopilotRouteImport } from './routes/api/public/cron.daily-autopilot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTargetingRoute = AuthenticatedTargetingRouteImport.update({
  id: '/targeting',
  path: '/targeting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalRoute = AuthenticatedApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksInboundEmailRoute =
  ApiPublicWebhooksInboundEmailRouteImport.update({
    id: '/api/public/webhooks/inbound-email',
    path: '/api/public/webhooks/inbound-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSendOutboundRoute =
  ApiPublicCronSendOutboundRouteImport.update({
    id: '/api/public/cron/send-outbound',
    path: '/api/public/cron/send-outbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailyAutopilotRoute =
  ApiPublicCronDailyAutopilotRouteImport.update({
    id: '/api/public/cron/daily-autopilot',
    path: '/api/public/cron/daily-autopilot',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approval': typeof AuthenticatedApprovalRoute
  '/board': typeof AuthenticatedBoardRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targeting': typeof AuthenticatedTargetingRoute
  '/api/public/cron/daily-autopilot': typeof ApiPublicCronDailyAutopilotRoute
  '/api/public/cron/send-outbound': typeof ApiPublicCronSendOutboundRoute
  '/api/public/webhooks/inbound-email': typeof ApiPublicWebhooksInboundEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approval': typeof AuthenticatedApprovalRoute
  '/board': typeof AuthenticatedBoardRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targeting': typeof AuthenticatedTargetingRoute
  '/api/public/cron/daily-autopilot': typeof ApiPublicCronDailyAutopilotRoute
  '/api/public/cron/send-outbound': typeof ApiPublicCronSendOutboundRoute
  '/api/public/webhooks/inbound-email': typeof ApiPublicWebhooksInboundEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/approval': typeof AuthenticatedApprovalRoute
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/targeting': typeof AuthenticatedTargetingRoute
  '/api/public/cron/daily-autopilot': typeof ApiPublicCronDailyAutopilotRoute
  '/api/public/cron/send-outbound': typeof ApiPublicCronSendOutboundRoute
  '/api/public/webhooks/inbound-email': typeof ApiPublicWebhooksInboundEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/approval'
    | '/board'
    | '/business'
    | '/dashboard'
    | '/inbox'
    | '/leads'
    | '/settings'
    | '/targeting'
    | '/api/public/cron/daily-autopilot'
    | '/api/public/cron/send-outbound'
    | '/api/public/webhooks/inbound-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/approval'
    | '/board'
    | '/business'
    | '/dashboard'
    | '/inbox'
    | '/leads'
    | '/settings'
    | '/targeting'
    | '/api/public/cron/daily-autopilot'
    | '/api/public/cron/send-outbound'
    | '/api/public/webhooks/inbound-email'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/approval'
    | '/_authenticated/board'
    | '/_authenticated/business'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/leads'
    | '/_authenticated/settings'
    | '/_authenticated/targeting'
    | '/api/public/cron/daily-autopilot'
    | '/api/public/cron/send-outbound'
    | '/api/public/webhooks/inbound-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronDailyAutopilotRoute: typeof ApiPublicCronDailyAutopilotRoute
  ApiPublicCronSendOutboundRoute: typeof ApiPublicCronSendOutboundRoute
  ApiPublicWebhooksInboundEmailRoute: typeof ApiPublicWebhooksInboundEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/targeting': {
      id: '/_authenticated/targeting'
      path: '/targeting'
      fullPath: '/targeting'
      preLoaderRoute: typeof AuthenticatedTargetingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approval': {
      id: '/_authenticated/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof AuthenticatedApprovalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/inbound-email': {
      id: '/api/public/webhooks/inbound-email'
      path: '/api/public/webhooks/inbound-email'
      fullPath: '/api/public/webhooks/inbound-email'
      preLoaderRoute: typeof ApiPublicWebhooksInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/send-outbound': {
      id: '/api/public/cron/send-outbound'
      path: '/api/public/cron/send-outbound'
      fullPath: '/api/public/cron/send-outbound'
      preLoaderRoute: typeof ApiPublicCronSendOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-autopilot': {
      id: '/api/public/cron/daily-autopilot'
      path: '/api/public/cron/daily-autopilot'
      fullPath: '/api/public/cron/daily-autopilot'
      preLoaderRoute: typeof ApiPublicCronDailyAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApprovalRoute: typeof AuthenticatedApprovalRoute
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTargetingRoute: typeof AuthenticatedTargetingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApprovalRoute: AuthenticatedApprovalRoute,
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTargetingRoute: AuthenticatedTargetingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronDailyAutopilotRoute: ApiPublicCronDailyAutopilotRoute,
  ApiPublicCronSendOutboundRoute: ApiPublicCronSendOutboundRoute,
  ApiPublicWebhooksInboundEmailRoute: ApiPublicWebhooksInboundEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
